name: cicd_tutorial
description: Demo app for Flutter + Firebase CI/CD

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  flutterfire_ui: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    git:
      url: https://github.com/nolandg/flutter
      path: packages/integration_test
      ref: fix-screenshots

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/