version: 2.1
jobs:
  build:
    docker:
      - image: bmonkman/node-flutter
      # - image: noland/flutter-circleci-demo:v1
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline!'
            flutter --version