version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.1.0

jobs:
  build:
    docker:
      - image: bmonkman/node-flutter
      # - image: noland/flutter-circleci-demo:v1
    steps:
      - browser-tools/install-chrome:
          chrome-version: 99.0.4844.74
      - browser-tools/install-chromedriver
      - checkout
      - run:
          name: Print flutter doctor
          command: flutter doctor
      - run:
          name: Run Unit Tests
          command: flutter test