version: 2.1
jobs:
  build:
    docker:
      - image: bmonkman/node-flutter
      # - image: noland/flutter-circleci-demo:v1
    steps:
      - checkout
      - run:
          name: Check Flutter Version
          command: flutter doctor
      - run:
          name: Run Unit Tests
          command: flutter test